import { t } from 'common/components';
import _ from 'lodash';

const definedKeys = {
  aadharNo: t('aadhaarNo'),
  firstName: t('labelIn', { label: t('asName', { type: t('first') }), type: t('english') }),
  middleName: t('labelIn', { label: t('asName', { type: t('middle') }), type: t('english') }),
  lastName: t('labelIn', { label: t('asName', { type: t('last') }), type: t('english') }),
  firstNameInLcl: t('labelIn', { label: t('asName', { type: t('first') }), type: t('malayalam') }),
  middleNameInLcl: t('labelIn', { label: t('asName', { type: t('middle') }), type: t('malayalam') }),
  lastNameInLcl: t('labelIn', { label: t('asName', { type: t('last') }), type: t('malayalam') }),
  mobileNumber: t('mobileNo'),
  isAnySpouseLiving: t('isAnySpouseLivingIn'),
  noOfSpouseLiving: t('noOfSpousesLivingIn'),
  guardianAadhaarNo: t('asAadhaarNo', { type: t('guardian_s') }),
  guardianName: t('labelIn', { label: t('asName', { type: t('guardian_s') }), type: t('english') }),
  guardianNameInLcl: t('labelIn', { label: t('asName', { type: t('guardian_s') }), type: t('malayalam') }),
  aadharLinkedMobileNumber: t('aadhaarLinkedMobileNo'),
  marriageDistrict: t('district'),
  marriageLBType: t('localBodyType'),
  marriageLocalBody: t('localBody'),
  homeWard: t('ward'),
  homeWardId: t('ward'),
  publicWardId: t('ward'),
  homeTaluk: t('taluk'),
  homeVillage: t('village'),
  homeVillageId: t('village'),
  publicVillageId: t('village'),
  homeLandmark: t('landmark'),
  homeLocality: t('labelIn', { label: t('locality'), type: t('english') }),
  publicLocalityName: t('labelIn', { label: t('locality'), type: t('english') }),
  homeLocalityName: t('labelIn', { label: t('locality'), type: t('english') }),
  homeLocalityInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  publicLocalityNameInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  homeLocalityNameInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  homeStreetName: t('labelIn', { label: t('street'), type: t('english') }),
  publicStreetName: t('labelIn', { label: t('street'), type: t('english') }),
  homeStreetInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  publicStreetNameInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  homeStreetNameInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  homeHouseNoName: t('labelIn', { label: t('houseNoAndName'), type: t('english') }),
  houseNoName: t('labelIn', { label: t('houseNoAndName'), type: t('english') }),
  houseNoNameInLcl: t('labelIn', { label: t('houseNoAndName'), type: t('malayalam') }),
  homeHouseNoNameInLcl: t('labelIn', { label: t('houseNoAndName'), type: t('malayalam') }),
  homeStreet: t('labelIn', { label: t('street'), type: t('english') }),
  homePostOffice: t('postOffice'),
  publicPostOffice: t('postOffice'),
  homePinCode: t('pinCode'),
  publicPinCode: t('pinCode'),
  privateWard: t('ward'),
  privateTaluk: t('taluk'),
  privateVillage: t('village'),
  privateLandmark: t('landmark'),
  privateLocality: t('labelIn', { label: t('locality'), type: t('english') }),
  privateLocalityInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  privateStreetInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  privateHouseNoName: t('labelIn', { label: t('houseNoAndName'), type: t('english') }),
  privateHouseNoNameInLcl: t('labelIn', { label: t('houseNoAndName'), type: t('malayalam') }),
  privateStreet: t('labelIn', { label: t('street'), type: t('english') }),
  publicWard: t('ward'),
  publicTaluk: t('taluk'),
  publicVillage: t('village'),
  publicLandmark: t('landmark'),
  publicPlaceType: t('publicPlaceType'),
  publicLocality: t('labelIn', { label: t('locality'), type: t('english') }),
  publicLocalityInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  publicStreetInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  publicHouseNoName: t('labelIn', { label: t('houseNoAndName'), type: t('english') }),
  publicHouseNoNameInLcl: t('labelIn', { label: t('houseNoAndName'), type: t('malayalam') }),
  publicStreet: t('labelIn', { label: t('street'), type: t('english') }),
  houseNoAndNameInLcl: t('labelIn', { label: t('houseNoAndName'), type: t('malayalam') }),
  streetInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  localityInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  talukTehsil: `${t('tehsil')}/${t('taluk')}`,
  townVillage: t('asName', { type: `${t('town')}/${t('village')}` }),
  stateProvince: t('asName', { type: `${t('state')}/${t('province')}` }),
  stateProvinceInLcl: t('asName', { type: `${t('state')}/${t('province')} (${t('malayalam')})` }),
  addressLine1: t('labelIn', { label: t('addressLine1'), type: t('english') }),
  addressLine2: t('labelIn', { label: t('addressLine2'), type: t('english') }),
  addressLine1InLcl: t('labelIn', { label: t('addressLine1'), type: t('malayalam') }),
  addressLine2InLcl: t('labelIn', { label: t('addressLine2'), type: t('malayalam') }),
  hospitalTypeId: t('hospitalType'),
  hospitalId: t('labelIn', { label: t('asName', { type: t('hospital_s') }), type: t('english') }),
  institutionType: t('institutionType'),
  institutionNameId: t('labelIn', { label: t('asName', { type: t('institution_s') }), type: t('english') }),
  vehicleType: t('vehicleType'),
  vehicleRegistrationNo: t('vehicleRegistrationNo'),
  vehicleTravellingTo: t('labelIn', { label: t('vehicleTravelingTo'), type: t('english') }),
  vehicleTravellingFrom: t('labelIn', { label: t('vehicleTravelingFrom'), type: t('english') }),
  placeOfHalt: t('labelIn', { label: t('placeOfFirstHalt'), type: t('localBody') }),
  vehicleTravellingFromLcl: t('labelIn', { label: t('vehicleTravelingFrom'), type: t('malayalam') }),
  vehicleTravellingToLcl: t('labelIn', { label: t('vehicleTravelingTo'), type: t('malayalam') }),
  lbWard: t('labelIn', { label: t('localBodyWard'), type: t('placeOfHalt') }),
  villageId: t('village'),
  wardId: t('ward'),
  districtId: t('district'),
  lbTypeId: t('localBodyType'),
  lbId: t('localBody'),
  placeOfBirthId: t('placeOfBirth'),
  localityName: t('labelIn', { label: t('locality'), type: t('english') }),
  streetName: t('labelIn', { label: t('street'), type: t('english') }),
  localityNameInLcl: t('labelIn', { label: t('locality'), type: t('malayalam') }),
  streetNameInLcl: t('labelIn', { label: t('street'), type: t('malayalam') }),
  pinCode: t('pinCode'),
  postOffice: t('postOffice'),
  chewingTobaccoYears: t('habituallyForYears'),
  drinkingAlcoholYears: t('habituallyForYears'),
  familyContactMobileNumber: t('familyContactMobileNo'),
  name: t('labelIn', { label: t('name'), type: t('english') }),
  nameInLcl: t('labelIn', { label: t('name'), type: t('malayalam') }),
  otherSignificantConditions: t('causeOfDeath'),
  aadharUIDNotAvailable: t('aadharUidNotAvailable'),
  parentOrGuardian: t('parentGuardianOfHusband'),
  AADHAAR_NUMBER_OF_DECEASED: t('aadhaarNumberOfDeceased'),
  NAME_CORRECTION: t('nameCorrection'),
  SEX: t('sex'),
  DATE_OF_DEATH: t('dateOfDeath'),
  PLACE_OF_DEATH: t('placeOfDeath'),
  NAME_OF_MOTHER: t('nameOfMother'),
  AADHAAR_NUMBER_OF_MOTHER: t('aadhaarNoOfMother'),
  NAME_OF_FATHER: t('nameOfFather'),
  AADHAAR_NUMBER_OF_FATHER: t('aadhaarNoOfFather'),
  NAME_OF_HUSBAND_WIFE: t('nameOfHusband/Wife'),
  AADHAAR_NUMBER_OF_HUSBAND_WIFE: t('aadhaarNoOfHusband/Wife'),
  ADDRESS_OF_DECEASED: t('addressOfDeceased'),
  PREVIEW: t('preview'),
  dateOfArrivalInIndia: t('dateOfArrivalIndia'),
  rdoProceedings: t('rdoProceedings'),
  childNameNotProvided: t('childNameNotProvided'),
  countryOfBirth: t('country'),
  natureOfMedicalAttention: t('natureOfMedicalAttentionAtDelivery'),
  weightAt: t('labelIn', { label: t('weightAtTheTimeOfBirth'), type: t('kg') }),
  placeOfBirthInEn: t('labelIn', { label: t('placeOfBirth'), type: t('english') }),
  placeOfBirthInLcl: t('labelIn', { label: t('placeOfBirth'), type: t('malayalam') }),
  stateOrProvinceOrRegionInEn: t('labelIn', { label: `${t('state')}/${t('province')}/${t('region')}`, type: t('english') }),
  stateOrProvinceOrRegionInLcl: t('labelIn', { label: `${t('state')}/${t('province')}/${t('region')}`, type: t('malayalam') }),
  ageAtTheTimeOfBirth: t('ageOfMotherAtTimeOfBirth'),
  ageAtTheTimeOfMarriage: t('ageOfMotherAtTimeOfMarriage'),
  motherMaritalStatus: t('mothersMaritalStatus'),
  parentEmailId: t('parentsEmail'),
  initiatorType: t('initiator'),
  aadhar: t('concatLabel', { label: t('initiator'), type: t('aadhaarNo') }),
  contactNo: t('concatLabel', { label: t('contact'), type: t('number') }),
  motherAadhaarNo: t('concatLabel', { label: t('mother_s'), type: t('aadhaarNo') }),
  fatherAadhaarNo: t('concatLabel', { label: t('father_s'), type: t('aadhaarNo') }),
  motherEducation: t('concatLabel', { label: t('mother_s'), type: t('education') }),
  fatherEducation: t('concatLabel', { label: t('father_s'), type: t('education') }),
  motherNationality: t('concatLabel', { label: t('mother_s'), type: t('nationality') }),
  fatherNationality: t('concatLabel', { label: t('father_s'), type: t('nationality') }),
  motherOccupation: t('concatLabel', { label: t('mother_s'), type: t('occupation') }),
  fatherOccupation: t('concatLabel', { label: t('father_s'), type: t('occupation') }),
  motherPassportNo: t('concatLabel', { label: t('mother_s'), type: t('passportNo') }),
  fatherPassportNo: t('concatLabel', { label: t('father_s'), type: t('passportNo') }),
  motherName: t('labelIn', { label: t('asName', { type: t('mother_s') }), type: t('english') }),
  motherNameInLcl: t('labelIn', { label: t('asName', { type: t('mother_s') }), type: t('malayalam') }),
  fatherName: t('labelIn', { label: t('asName', { type: t('father_s') }), type: t('english') }),
  fatherNameInLcl: t('labelIn', { label: t('asName', { type: t('father_s') }), type: t('malayalam') }),
  noOfChildrenBornAliveIncludingThisChild: t('noOfChildBornAliveIncludingThisChild'),
  DATE_OF_BIRTH_HUSBAND: t('ageAndDateOfBirthOfHusbandLabel'),
  DATE_OF_BIRTH_WIFE: t('ageAndDateOfBirthOfWifeLabel'),
  AADHAAR_NUMBER_OF_HUSBAND: t('aadhaarNoOfHusband'),
  AADHAAR_NUMBER_OF_WIFE: t('aadhaarNoOfWife'),
  NAME_OF_GUARDIAN_HUSBAND: t('nameOfGuardianOfHusband'),
  NAME_OF_GUARDIAN_WIFE: t('nameOfGuardianOfWife'),
  AADHAAR_NUMBER_OF_GUARDIAN: t('aadhaarNoOfGuardian'),
  NAME_OF_MOTHER_HUSBAND: t('nameOfMotherOfHusband'),
  NAME_OF_FATHER_HUSBAND: t('nameOfFatherOfHusband'),
  NAME_OF_MOTHER_WIFE: t('nameOfMotherOfWife'),
  NAME_OF_FATHER_WIFE: t('nameOfFatherOfWife'),
  DATE_OF_MARRIAGE: t('dateOfMarriage'),
  PLACE_OF_MARRIAGE: t('placeOfMarriage'),
  NAME_CORRECTION_HUSBAND: t('nameOfHusband'),
  NAME_CORRECTION_WIFE: t('nameOfWife'),
  ADDRESS_OF_HUSBAND: t('addressOfHusband'),
  ADDRESS_OF_WIFE: t('addressOfWife')
};

export const translateKey = (key) => _.get(definedKeys, key, t(key));
